name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm install
    - name: Run the linter
      run: npm run lint
    - name: Build the code
      run: npm run build
    - name: Run tests
      run: npm run test
